Repository aleph-im/pyaleph, pull requests merged in 2022-02, with the labels that each got.

#148 [CI] Cache Docker images
  .github/workflows/pyaleph-ci.yml
Labels: enhancement

#144 Change: Sort pending messages by number of retries in processing
  src/aleph/jobs.py
  src/aleph/model/pending.py
Labels: enhancement

#181 [Docs] Use version in download links
  docs/conf.py
  docs/guides/install.rst
  docs/guides/upgrade.rst
Labels: enhancement

#185 Fix: Protect against wrong IPv4 format from 3rd party service.
  src/aleph/services/utils.py
  tests/services/test_utils.py
Labels: bug

#189 Fix: The `beta` docker image was used only for `chown`
  docs/guides/install.rst
  docs/guides/upgrade.rst
Labels: cleanup

#188 Change: Drop support for Python 3.6, require 3.8+
  .readthedocs.yml
  README.md
Labels: cleanup
